<?xml version="1.0" encoding="utf-8"?>
<assemblies timestamp="08/24/2023 14:18:25">
  <assembly name="TestProject.dll" environment="64-bit .NET .NET 7.0 [collection-per-class, parallel (8 threads)]" test-framework="xUnit.net 2.4.2.0" run-date="2023-08-24" run-time="14:18:25" total="1" passed="1" failed="0" skipped="0" time="0.608" errors="0">
    <errors />
    <collection total="1" passed="1" failed="0" skipped="0" name="Test collection for TestProject.UnitTest1" time="0.367">
      <test name="TestProject.UnitTest1.AsyncExceptionCallStack" type="TestProject.UnitTest1" method="AsyncExceptionCallStack" time="0.3668128" result="Pass">
        <output><![CDATA[Begin Observing Exception: System.Threading.Tasks.TaskCanceledException
Throwing Frame: [ThrowForNonSuccess, 0x26]
Begin Checking Thread Frames:
- [ValidateExceptionStackFrame, 0xB5]
- [FirstChanceExceptionCallback, 0x41]
- [<AsyncExceptionCallStack>b__0, 0x6]
- [ThrowForNonSuccess, 0x26]
End Checking Thread Frames:
End Observing Exception: System.Threading.Tasks.TaskCanceledException
]]></output>
      </test>
    </collection>
  </assembly>
</assemblies>